# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.mollifier]
github = "mollifier/cd-gitroot"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.docker-zsh-completion]
github = "felixr/docker-zsh-completion"

[plugins.autopair]
github = "hlissner/zsh-autopair"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

[plugins.git-open]
github = "paulirish/git-open"

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"
